// <auto-generated />
using System;
using Feuerwehr.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Feuerwehr.Server.Migrations
{
    [DbContext(typeof(FeuerwehrDbContext))]
    [Migration("20260629091957_AddSeatsAssignedToFireDepartmentTrainingCourse")]
    partial class AddSeatsAssignedToFireDepartmentTrainingCourse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("Hydrants_Id_seq");

            modelBuilder.Entity("Feuerwehr.Common.Models.Hydrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"Hydrants_Id_seq\"')");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<int>("NominalDiameter")
                        .HasColumnType("integer")
                        .HasColumnName("DN_Diameter");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("WaterSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Hydrants", (string)null);
                });

            modelBuilder.Entity("Feuerwehr.Server.Models.FireDepartment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactPersonEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactPersonName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FireDepartment", (string)null);
                });

            modelBuilder.Entity("Feuerwehr.Server.Models.FireDepartmentTrainingCourse", b =>
                {
                    b.Property<int>("FireDepartmentId")
                        .HasColumnType("integer");

                    b.Property<int>("TrainingCourseId")
                        .HasColumnType("integer");

                    b.Property<int>("SeatsAssigned")
                        .HasColumnType("integer");

                    b.HasKey("FireDepartmentId", "TrainingCourseId");

                    b.HasIndex("TrainingCourseId");

                    b.ToTable("FireDepartmentTrainingCourses", (string)null);
                });

            modelBuilder.Entity("Feuerwehr.Server.Models.TrainingCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TrainingCourse", (string)null);
                });

            modelBuilder.Entity("Feuerwehr.Common.Models.Hydrant", b =>
                {
                    b.OwnsOne("Feuerwehr.Common.Models.Address", "Address", b1 =>
                        {
                            b1.Property<int>("HydrantId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("AdditionalInfo")
                                .HasColumnType("text")
                                .HasColumnName("AdditionalInfo");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("City");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("HouseNumber");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Street");

                            b1.HasKey("HydrantId");

                            b1.ToTable("Hydrants");

                            b1.WithOwner()
                                .HasForeignKey("HydrantId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Feuerwehr.Server.Models.FireDepartmentTrainingCourse", b =>
                {
                    b.HasOne("Feuerwehr.Server.Models.FireDepartment", "FireDepartment")
                        .WithMany("FireDepartmentTrainingCourses")
                        .HasForeignKey("FireDepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Feuerwehr.Server.Models.TrainingCourse", "TrainingCourse")
                        .WithMany("FireDepartmentTrainingCourses")
                        .HasForeignKey("TrainingCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FireDepartment");

                    b.Navigation("TrainingCourse");
                });

            modelBuilder.Entity("Feuerwehr.Server.Models.FireDepartment", b =>
                {
                    b.Navigation("FireDepartmentTrainingCourses");
                });

            modelBuilder.Entity("Feuerwehr.Server.Models.TrainingCourse", b =>
                {
                    b.Navigation("FireDepartmentTrainingCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
