apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: true
      timeInterval: 15s
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: tempo

  - name: Prometheus-Internal
    uid: prometheus-internal
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
