// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using de.openelp.feuerwehr.infrastructure;

#nullable disable

namespace de.openelp.feuerwehr.infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402122629_AddInventoryItemRelationship")]
    partial class AddInventoryItemRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("de.openelp.feuerwehr.domain.Hydrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hydrants");
                });

            modelBuilder.Entity("de.openelp.feuerwehr.domain.InventoryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InventoryCategories");
                });

            modelBuilder.Entity("de.openelp.feuerwehr.domain.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("NextInspectionDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("de.openelp.feuerwehr.domain.InventoryItemRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChildItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParentItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RelationshipLabelId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChildItemId");

                    b.HasIndex("RelationshipLabelId");

                    b.HasIndex("ParentItemId", "ChildItemId", "RelationshipLabelId")
                        .IsUnique();

                    b.ToTable("InventoryItemRelationships");
                });

            modelBuilder.Entity("de.openelp.feuerwehr.domain.ItemRelationshipLabel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ItemRelationshipLabels");
                });

            modelBuilder.Entity("de.openelp.feuerwehr.domain.InventoryItem", b =>
                {
                    b.HasOne("de.openelp.feuerwehr.domain.InventoryCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("de.openelp.feuerwehr.domain.InventoryItemRelationship", b =>
                {
                    b.HasOne("de.openelp.feuerwehr.domain.InventoryItem", "ChildItem")
                        .WithMany()
                        .HasForeignKey("ChildItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("de.openelp.feuerwehr.domain.InventoryItem", "ParentItem")
                        .WithMany("ChildRelationships")
                        .HasForeignKey("ParentItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("de.openelp.feuerwehr.domain.ItemRelationshipLabel", "RelationshipLabel")
                        .WithMany("Relationships")
                        .HasForeignKey("RelationshipLabelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildItem");

                    b.Navigation("ParentItem");

                    b.Navigation("RelationshipLabel");
                });

            modelBuilder.Entity("de.openelp.feuerwehr.domain.InventoryCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("de.openelp.feuerwehr.domain.InventoryItem", b =>
                {
                    b.Navigation("ChildRelationships");
                });

            modelBuilder.Entity("de.openelp.feuerwehr.domain.ItemRelationshipLabel", b =>
                {
                    b.Navigation("Relationships");
                });
#pragma warning restore 612, 618
        }
    }
}
