version: '3.8'

services:
  app:
    container_name: feuerwehr-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - postgres
      - redis
      - postgresAuth
    environment:
      DOTNET_NOLOGO: "true"
      DOTNET_CLI_TELEMETRY_OPTOUT: "1"
      POSTGRES_PASSWORD: feuerwehr
      POSTGRES_USER: feuerwehr
      POSTGRES_DB: feuerwehr
      POSTGRES_HOST: postgres
      POSTGRES_AUTH_DB: auth_db
      POSTGRES_AUTH_USER: Auth
      POSTGRES_AUTH_PASSWORD: Auth
      POSTGRES_AUTH_HOST: postgresAuth
      REDIS_HOST: redis
      ASPNETCORE_ENVIRONMENT: Development
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      JWT_SECRET: MeinSehrGeheimerUndLangerSchlüssel
      JWT_ISSUER: AuthService
      JWT_AUDIENCE: FeuerwehrAPI
    network_mode: service:postgres

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: feuerwehr
      POSTGRES_USER: feuerwehr
      POSTGRES_DB: feuerwehr

  postgresAuth:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: Auth
      POSTGRES_PASSWORD: Auth

  redis:
    image: redis
    network_mode: service:postgres
